version: '3'
services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432
    volumes: 
      - ./db/dbinit.sql:/docker-entrypoint-initdb.d/create_tables.sql
      #- db-data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1

  backend:
    build: ./backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: always
        delay: 10s
        max_attempts: 3

  frontend:
    build: ./frontend
    ports:
      - 80:80

#volumes:
  #db-data: